version: "3.9"
services:
  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3000:3000"
    environment:
      - BACKEND_ADDRESS=verifiable-unlearning
      - BACKEND_PORT=5000
  
  verifiable-unlearning:
    build: 
      context: './verifiable-unlearning'
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'